new-file.py
This is a PR to demonstrate the template for the dev team
- [N/A] New and existing tests pass locally with my changes.
- Issue #6 
- No test changes
Today was productive!
=> add new python file to demo pr template:

.github/ISSUE_TEMPLATE/✨-feature-request.md, .github/ISSUE_TEMPLATE/🐞-bug-report.md, .github/ISSUE_TEMPLATE/📌-task.md
This commit adds 3 issue templates: Bug Report, Feature Request, Task.
=> Engineering Fundamentals: Add Issue Templates

CONTRIBUTING.md
Project has proper documentation on coding standards, guidelines, and resources including making pull requests.
=> CONTRIBUTING.md change

src/autopatchdatatypes/autopatchdatatypes/test_crash_detail.py
This PR adds automated tests for crashdetail datatype
adds 8 automated pytest tests
=> add automated tests for crashdetail datatype

.github/workflows/release.yml, Taskfile.yml
This PR fixes invocation of package install in root task for release task CI
- [N/A] New and existing tests pass locally with my changes.
=> release(v0.2.0): fix invocation of package install in root task for CI

.github/workflows/release.yml
This PR better aligns the first draft release pipeline with the test coverage pipeline 
- [ x I have performed a self-review of my own code.
- [N/A] New and existing tests pass locally with my changes.
=> release(v0.2.2): Align first draft release pipeline with test pipeline

.github/workflows/pre-release.yml
=> release(v0.2.3): fix prerelease pipeline with sparse clonse of assets/input_codebase

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> write permissions for release pipeline

.github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/super-linter.yml, .github/workflows/test-coverage.yml
=> feature(releasepipeline): align release pipeline with prerelease

.github/workflows/release.yml
v0.3.0          Release v0.3.0-alpha
Changes:
- Added MessageBrokerClient class as Facade for pub/sub messaging clients
- Added Patch Evaluation Component (first alpha revision)
- Add shared library for common functions
- Add compose support for patch evaluation component
- General Bug Fixes and Improvements
=> release(v0.3.0): re-add correct test config files for CI

.github/workflows/pre-release.yml, .github/workflows/release.yml
v0.3.0          Release v0.3.0-alpha
Changes:
- Added MessageBrokerClient class as Facade for pub/sub messaging clients
- Added Patch Evaluation Component (first alpha revision)
- Add shared library for common functions
- Add compose support for patch evaluation component
- General Bug Fixes and Improvements
=> release(CI): typo fix on artifact upload

src/patch-evaluation-service/pyproject.toml
=> release(v0.4.1-alpha): set patch eval pyproject toml to v0.4.1

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This PR add Joern to the devcontainer
Rebuilt devcontainer
=> feature(devtools-joern): add jeorn to development container

docs/TechnicalSpikes/005.meta-infer.md
simple technical spike looking at meta infer
- [N/A] New and existing tests pass locally with my changes.
Github Issue #65
=> docs(technical-spike): simple technical spike looking at meta infer

src/fuzzing-service/Dockerfile
This PR uses layered docker builds for fuzzing service to cut the runtime size of the image
=> feature(fuzzing-service): use layered docker builds for fuzzing service

docker-compose.yml, src/code-property-graph-generator/Dockerfile, src/code-property-graph-generator/README.md, src/code-property-graph-generator/code_property_graph_generator.py, src/code-property-graph-generator/test_code_property_graph_generator.py
This PR cuts down the size of the cpg-generator docker container to use layered builds
=> feature(cpg generator): use layered builds for cpg generator

src/patch-evaluation-service/Dockerfile
this PR adds layered builds for patch eval container to cut runtime image size
=> layered builds for patch eval container

.gitattributes
=> should ignore ipynb from repo stats

.devcontainer/Dockerfile
This change pins software-properties-common in the devcontainer to the noble upstream
=> Use software-properties-common v0.99.48

pyproject.toml, src/autopatchdatatypes/pyproject.toml, src/autopatchpubsub/pyproject.toml, src/autopatchshared/pyproject.toml, src/code-property-graph-generator/Dockerfile, src/code-property-graph-generator/config/config.json, src/code-property-graph-generator/config/dev-config.json, src/code-property-graph-generator/pyproject.toml, src/code-property-graph-generator/requirements.txt, src/fuzzing-service/Dockerfile, src/fuzzing-service/config/config.json, src/fuzzing-service/config/dev-config.json, src/fuzzing-service/pyproject.toml, src/fuzzing-service/requirements.txt, src/llm-dispatch-service/Dockerfile, src/llm-dispatch-service/config/config.json, src/llm-dispatch-service/config/dev-config.json, src/llm-dispatch-service/pyproject.toml, src/llm-dispatch-service/requirements.txt, src/patch-evaluation-service/Dockerfile, src/patch-evaluation-service/config/config.json, src/patch-evaluation-service/config/dev-config.json, src/patch-evaluation-service/pyproject.toml, src/patch-evaluation-service/requirements.txt
- new component llm-dispatch
- Feature/docker container releases
- General improvements
- use layered docker builds for fuzzing service, cpg generator, patch eval
- technical docs prototype(cpg-notebooks): add code property graph generator early research notebooks
- General Bug fixes and improvements
* https://github.com/sysec-uic/AutoPatch-LLM/pkgs/container/autopatch-llm%2Ffuzzing-service
* https://github.com/sysec-uic/AutoPatch-LLM/pkgs/container/autopatch-llm%2Fpatch-evaluation-service
* https://github.com/sysec-uic/AutoPatch-LLM/pkgs/container/autopatch-llm%2Fllm-dispatch-service
**Full Changelog**: https://github.com/sysec-uic/AutoPatch-LLM/compare/v0.5.0...v0.6.0
- **fuzzing-service**: use layered docker builds for fuzzing service (#97) …
=> release(v0.6.1-alpha): first revision llm dispatch component, docker container releases

src/llm-dispatch-service/config/config.json
bugfix typo in config var name
=> bugfix typo in config var name

docker-compose.yml, src/autopatchdatatypes/autopatchdatatypes/patch_response.py, src/code-property-graph-generator/config/config.json, src/code-property-graph-generator/config/dev-config.json, src/fuzzing-service/config/config.json, src/fuzzing-service/config/dev-config.json, src/patch-evaluation-service/config/config.json, src/patch-evaluation-service/config/dev-config.json
Release v0.7.0-alpha
- llm-dispatch component now produces PatchResponse strong types as CloudEvents
- autopatchpubsub now re-supports fully concurrent message publishing for individual service
=> release(v0.7.0-alpha)

src/autopatchpubsub/autopatchpubsub/message_broker_client.py, src/code-property-graph-generator/config/config.json, src/code-property-graph-generator/config/dev-config.json, src/fuzzing-service/config/config.json, src/fuzzing-service/config/dev-config.json, src/fuzzing-service/test_fuzzing_service.py, src/llm-dispatch-service/config/config.json, src/llm-dispatch-service/config/dev-config.json, src/llm-dispatch-service/test_llm_dispatch_service.py, src/patch-evaluation-service/config/config.json, src/patch-evaluation-service/config/dev-config.json, src/patch-evaluation-service/test_patch_evaluation_service.py
Logger was throwing a stacktrace on debug logging, removed that statement 
automated tests pass
=> release(v0.9.0-beta): bugfix remove debug logger decoding, update configs for app to report its up date version
